server:
  port: 8095


spring:
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml